import json
from pathlib import Path

path = Path('/home/ubuntu/work/CALCULADORA_PENAL/src/data/tiposPenais.json')
catalog = json.loads(path.read_text())
existing = {record['id'] for record in catalog['registros']}
SOURCE = 'https://www.planalto.gov.br/ccivil_03/decreto-lei/del2848.htm'
CUTOFF = catalog['dataCorte']

def make_record(id, device, name, desc, minimum, maximum, penalty, keywords, nature='basica', parent=None, laws=None, observation=None):
    return {
        'id': id, 'nomeJuridico': name, 'aliases': [], 'classe': 'crime', 'jurisdicao': 'comum', 'modulo': 'Código Penal',
        'norma': 'Decreto-Lei nº 2.848/1940', 'dispositivo': device, 'naturezaFigura': nature, 'tipoPaiId': parent,
        'descricaoObjetiva': desc,
        'pena': {'minimoMeses': minimum, 'maximoMeses': maximum, 'unidadePrincipal': 'meses', 'descricao': penalty, 'multa': None},
        'vigencia': {'estado': 'vigente', 'inicioVigenciaRedacao': '1940-12-07', 'dataConsulta': CUTOFF, 'estadoConferencia': 'pendente', 'observacoes': observation or 'Crime contra a fé pública localizado na fonte oficial; inventário e enriquecimento pendentes antes do cálculo.'},
        'fonteOficial': SOURCE, 'leiCriadoraOuModificadora': laws or ['Decreto-Lei nº 2.848/1940'], 'inventarioValidado': False,
        'enriquecimentoValidado': False, 'usavelNaCalculadora': False,
        'enriquecimento': {'bemJuridico': None, 'sujeitoAtivo': None, 'sujeitoPassivo': None, 'elementoSubjetivo': None, 'consumacao': None, 'tentativa': None, 'formaCulposa': None, 'acaoPenal': None, 'competencia': 'comum', 'procedimento': None, 'rito': None, 'hediondez': None, 'qualificadoras': [], 'majorantes': [], 'minorantes': [], 'agravantesAtenuantes': [], 'extincaoPunibilidade': [], 'jurisprudenciaQualificada': [], 'controversias': []},
        'palavrasChave': keywords,
    }
new = [
 make_record('cp-289','art. 289, caput','Moeda falsa','Falsificar, fabricando ou alterando, moeda metálica ou papel-moeda de curso legal no país ou no estrangeiro.',36,144,'Reclusão, de 3 a 12 anos, e multa.',['moeda falsa','papel-moeda']),
 make_record('cp-289-3','art. 289, § 3º','Emissão irregular de moeda por funcionário ou dirigente bancário','Funcionário público ou dirigente de banco de emissão fabricar, emitir ou autorizar moeda com título ou peso inferior ao legal, ou papel-moeda em quantidade superior à autorizada.',36,180,'Reclusão, de 3 a 15 anos, e multa.',['moeda falsa','emissão irregular'],'qualificada','cp-289'),
 make_record('cp-290','art. 290','Crimes assimilados ao de moeda falsa','Formar cédula com fragmentos verdadeiros, suprimir sinal de inutilização ou restituir à circulação cédula recolhida para inutilização.',24,96,'Reclusão, de 2 a 8 anos, e multa.',['moeda falsa','cédula inutilizada']),
 make_record('cp-291','art. 291','Petrechos para falsificação de moeda','Fabricar, adquirir, fornecer, possuir ou guardar objeto especialmente destinado à falsificação de moeda.',24,72,'Reclusão, de 2 a 6 anos, e multa.',['petrechos','falsificação de moeda']),
 make_record('cp-292','art. 292, caput','Emissão de título ao portador sem permissão legal','Emitir sem permissão legal nota, bilhete, ficha, vale ou título com promessa de pagamento em dinheiro ao portador ou sem indicação do beneficiário.',1,6,'Detenção, de 1 a 6 meses, ou multa.',['título ao portador','emissão irregular']),
 make_record('cp-292-pu','art. 292, parágrafo único','Uso de título ao portador sem permissão legal','Receber ou utilizar como dinheiro documento abrangido pelo art. 292.',0.5,3,'Detenção, de 15 dias a 3 meses, ou multa.',['título ao portador','uso irregular'],'qualificada','cp-292'),
 make_record('cp-293','art. 293, caput','Falsificação de papéis públicos','Falsificar selo de controle tributário, papel selado, papel de emissão legal, papel de crédito público, vale postal ou documento de arrecadação ou transporte público.',24,96,'Reclusão, de 2 a 8 anos, e multa.',['papéis públicos','selo tributário']),
 make_record('cp-293-2','art. 293, § 2º','Supressão de sinal de inutilização de papel público','Suprimir, em papel público legítimo, carimbo ou sinal de inutilização para torná-lo novamente utilizável.',12,48,'Reclusão, de 1 a 4 anos, e multa.',['papéis públicos','sinal de inutilização'],'qualificada','cp-293'),
 make_record('cp-293-4','art. 293, § 4º','Uso de papel público falsificado recebido de boa-fé','Usar ou restituir à circulação, após conhecer a falsidade ou alteração, papel público falsificado ou alterado recebido de boa-fé.',6,24,'Detenção, de 6 meses a 2 anos, ou multa.',['papéis públicos','boa-fé'],'qualificada','cp-293'),
 make_record('cp-294','art. 294','Petrechos de falsificação de papéis públicos','Fabricar, adquirir, fornecer, possuir ou guardar objeto especialmente destinado à falsificação de papéis públicos.',12,36,'Reclusão, de 1 a 3 anos, e multa.',['petrechos','papéis públicos']),
 make_record('cp-296','art. 296','Falsificação de selo ou sinal público','Falsificar selo público, selo ou sinal atribuído por lei a entidade ou autoridade pública, ou sinal público de tabelião.',24,72,'Reclusão, de 2 a 6 anos, e multa.',['selo público','sinal público']),
 make_record('cp-296-pu','art. 296, § 1º, III','Uso indevido de símbolo da Administração Pública','Alterar, falsificar ou fazer uso indevido de marcas, logotipos, siglas ou símbolos utilizados ou identificadores de órgãos ou entidades da Administração Pública.',24,72,'Reclusão, de 2 a 6 anos, e multa.',['símbolo público','Administração Pública'],'qualificada','cp-296',laws=['Decreto-Lei nº 2.848/1940','Lei nº 9.983/2000']),
 make_record('cp-297','art. 297','Falsificação de documento público','Falsificar total ou parcialmente documento público ou alterar documento público verdadeiro.',24,72,'Reclusão, de 2 a 6 anos, e multa.',['documento público','falsificação']),
 make_record('cp-298','art. 298','Falsificação de documento particular','Falsificar total ou parcialmente documento particular ou alterar documento particular verdadeiro.',12,60,'Reclusão, de 1 a 5 anos, e multa.',['documento particular','falsificação']),
 make_record('cp-299-publico','art. 299, caput, documento público','Falsidade ideológica em documento público','Omitir ou inserir declaração falsa ou diversa em documento público, para prejudicar direito, criar obrigação ou alterar a verdade sobre fato juridicamente relevante.',12,60,'Reclusão, de 1 a 5 anos, e multa.',['falsidade ideológica','documento público']),
 make_record('cp-299-particular','art. 299, caput, documento particular','Falsidade ideológica em documento particular','Omitir ou inserir declaração falsa ou diversa em documento particular, para prejudicar direito, criar obrigação ou alterar a verdade sobre fato juridicamente relevante.',12,36,'Reclusão, de 1 a 3 anos, e multa.',['falsidade ideológica','documento particular']),
 make_record('cp-300-publico','art. 300, documento público','Falso reconhecimento de firma ou letra em documento público','Reconhecer como verdadeira, no exercício de função pública, firma ou letra que não o seja em documento público.',12,60,'Reclusão, de 1 a 5 anos, e multa.',['firma falsa','documento público']),
 make_record('cp-300-particular','art. 300, documento particular','Falso reconhecimento de firma ou letra em documento particular','Reconhecer como verdadeira, no exercício de função pública, firma ou letra que não o seja em documento particular.',12,36,'Reclusão, de 1 a 3 anos, e multa.',['firma falsa','documento particular']),
 make_record('cp-301','art. 301, caput','Certidão ou atestado ideologicamente falso','Atestar ou certificar falsamente, em razão de função pública, fato ou circunstância que habilite alguém a obter cargo, isenção, serviço ou vantagem.',2/12,12,'Detenção, de 2 meses a 1 ano.',['certidão falsa','atestado falso']),
 make_record('cp-301-1','art. 301, § 1º','Falsidade material de atestado ou certidão','Falsificar atestado ou certidão, ou alterar certidão ou atestado verdadeiro, para prova de fato que habilite alguém a obter cargo, isenção ou vantagem.',0.25,24,'Detenção, de 3 meses a 2 anos.',['certidão falsa','falsidade material'],'qualificada','cp-301'),
 make_record('cp-302','art. 302','Falsidade de atestado médico','Dar o médico, no exercício da profissão, atestado falso.',1/12,12,'Detenção, de 1 mês a 1 ano.',['atestado médico falso']),
 make_record('cp-303','art. 303','Reprodução ou adulteração de selo ou peça filatélica','Reproduzir ou alterar selo ou peça filatélica de valor para coleção sem anotação visível da reprodução ou alteração.',12,36,'Detenção, de 1 a 3 anos, e multa.',['selo filatélico','adulteração']),
 make_record('cp-304','art. 304','Uso de documento falso','Fazer uso de papel falsificado ou alterado referido nos arts. 297 a 302.',None,None,'Pena correspondente à falsificação ou alteração do documento utilizado.',['uso de documento falso'],observation='A pena é remissiva e depende do documento-base; mantida sem faixa numérica para evitar estimativa indevida.'),
 make_record('cp-305-publico','art. 305, documento público','Supressão de documento público','Destruir, suprimir ou ocultar, em benefício próprio ou alheio ou em prejuízo de outrem, documento público verdadeiro de que não podia dispor.',24,72,'Reclusão, de 2 a 6 anos, e multa.',['supressão de documento','documento público']),
 make_record('cp-305-particular','art. 305, documento particular','Supressão de documento particular','Destruir, suprimir ou ocultar, em benefício próprio ou alheio ou em prejuízo de outrem, documento particular verdadeiro de que não podia dispor.',12,60,'Reclusão, de 1 a 5 anos, e multa.',['supressão de documento','documento particular']),
 make_record('cp-306','art. 306, caput','Falsificação de sinal de fiscalização pública','Falsificar ou usar marca ou sinal empregado pelo poder público no contraste de metal precioso ou na fiscalização alfandegária.',24,72,'Reclusão, de 2 a 6 anos, e multa.',['marca pública','fiscalização alfandegária']),
 make_record('cp-306-pu','art. 306, parágrafo único','Falsificação de sinal de fiscalização sanitária','Falsificar ou usar marca ou sinal empregado pela autoridade para fiscalização sanitária, autenticação, encerramento de objetos ou comprovação de formalidade legal.',12,36,'Reclusão ou detenção, de 1 a 3 anos, e multa.',['fiscalização sanitária','sinal público'],'qualificada','cp-306'),
 make_record('cp-307','art. 307','Falsa identidade','Atribuir-se ou atribuir a terceiro falsa identidade para obter vantagem ou causar dano.',0.25,12,'Detenção, de 3 meses a 1 ano, ou multa, se o fato não constitui elemento de crime mais grave.',['falsa identidade']),
 make_record('cp-308','art. 308','Uso de documento de identidade alheia','Usar como próprio ou ceder a outrem passaporte, título de eleitor, caderneta de reservista ou documento de identidade alheio.',1/3,24,'Detenção, de 4 meses a 2 anos, e multa, se o fato não constitui elemento de crime mais grave.',['documento alheio','identidade']),
 make_record('cp-309','art. 309','Fraude de lei sobre estrangeiros','Usar o estrangeiro, para entrar ou permanecer no território nacional, nome que não é o seu.',12,36,'Detenção, de 1 a 3 anos, e multa.',['estrangeiro','identidade falsa']),
 make_record('cp-309-pu','art. 309, parágrafo único','Atribuição de falsa qualidade a estrangeiro','Atribuir a estrangeiro falsa qualidade para promover sua entrada em território nacional.',12,48,'Reclusão, de 1 a 4 anos, e multa.',['estrangeiro','entrada irregular'],'qualificada','cp-309',laws=['Decreto-Lei nº 2.848/1940','Lei nº 9.426/1996']),
 make_record('cp-310','art. 310','Falsidade em prejuízo da nacionalização de sociedade','Prestar-se a figurar como proprietário ou possuidor de ação, título ou valor pertencente a estrangeiro quando a lei lhe veda essa propriedade ou posse.',6,36,'Detenção, de 6 meses a 3 anos, e multa.',['estrangeiro','sociedade','falsidade'],laws=['Decreto-Lei nº 2.848/1940','Lei nº 9.426/1996']),
 make_record('cp-311','art. 311','Adulteração de sinal identificador de veículo','Adulterar, remarcar ou suprimir número de chassi, monobloco, motor, placa ou sinal identificador de veículo ou componente sem autorização do órgão competente.',36,72,'Reclusão, de 3 a 6 anos, e multa.',['veículo','chassi','sinal identificador'],laws=['Decreto-Lei nº 2.848/1940','Lei nº 14.562/2023']),
 make_record('cp-311-3','art. 311, § 3º','Comércio de veículo com sinal identificador adulterado','Praticar em atividade comercial ou industrial as condutas de adquirir, transportar, ocultar, manter em depósito, fabricar, fornecer ou possuir objeto de falsificação, ou utilizar veículo com sinal adulterado.',48,96,'Reclusão, de 4 a 8 anos, e multa.',['veículo','sinal identificador','comércio'],'qualificada','cp-311',laws=['Decreto-Lei nº 2.848/1940','Lei nº 14.562/2023']),
]
for item in new:
    if item['id'] not in existing:
        catalog['registros'].append(item)
path.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + '\n')
print(f'added {sum(item["id"] not in existing for item in new)} public-faith records')
